spring.application.name=borrowing-service
server.port=8083

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/borrow_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:a}
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

# Resilience4j circuit breaker configuration
resilience4j.circuitbreaker.instances.borrowBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.borrowBreaker.failure-rate-threshold=50

#temporary for debug
logging.level.io.github.resilience4j=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG