spring.application.name=member-service
server.port=8081

# MySQL for Member service

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/member_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:a}
spring.jpa.hibernate.ddl-auto=update

# Connect to Eureka (the phonebook)

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
